### ISSUE TITLE
Great tool, couple suggestions

### ISSUE THREAD

**Issue by milosonator** [Pouja/tudscheduler#1]
Hey there,

couple of suggestions to make this better:
- Display the Quarter information in the list.
- Display the course code in the schedule
- Make the boxes in the schedule smaller, they are huge.

**Comment by Pouja** [comment]
Thanks for the suggestions!  

> Display the Quarter information in the list  

What do you mean exactly by that?

> Make the boxes in the schedule smaller, they are huge  

In width, height or both?

**Comment by milosonator** [comment]
Currently you cannot see which quarter(s) a course will be in from the list.

Height is too high.
Op 20 sep. 2015 13:46 schreef "Pouja" notifications@github.com:

**Comment by Pouja** [comment]
@milosonator I changed the height and added the course code ~~(it is possible you have reset the cache, for some reason GitHub pages keeps giving 304, even when my index.html is changed :/)~~ _Fixed it_.

For the quarter information, I tried to fit it with the EC and the info and add/remove button, but it gets quite messy. So if you have a suggesting on how it can be designed nicely, please let me know :sweat_smile: . You can even provide screen shot, or code it yourself. In [CourseTree.jsx](https://github.com/Pouja/tudscheduler/blob/master/scripts/components/CourseTree.jsx#L55-L78) you can find the lines which renders that part.
