### ISSUE TITLE
Apply markdown renderer or at least newline to br in course details.

### ISSUE THREAD

**Issue by dgroenewegen** [Pouja/tudscheduler#23]

**Comment by Pouja** [comment]
@dmgroenewegen is it only newline support? Or are there more markdown syntax expected in the course details?

**Comment by dgroenewegen** [comment]
It's not written in markdown but there's quite a few ad hoc enumerations with dashes or numbers which look a lot better in markdown. In the server-side application I run it through a markdown renderer, it also detects urls and makes them clickable, but that depends on the markdown variant. Newlines is the main problem so include that at least.
