### ISSUE TITLE
Cannot remove IN4391 cancelled course

### ISSUE THREAD

**Issue by joined** [Pouja/tudscheduler#24]
I added the Distributed Computing Systems course, that was announced as not being taught this year some days ago. Now I cannot remove it from my IEP form, if I try to do it I get this error in the console:

    Uncaught TypeError: Cannot read property 'id' of undefined(…)

**Comment by Pouja** [comment]
Thanks for the report, sorry to hear you are having some problems.
If you can, can mail me or post here (which you prefer), the content POST request that is being send when you try to remove it?

**Comment by joined** [comment]
I was able to remove the course by manually crafting the POST request to exclude the problematic courseId (which is "4709aee4-e3c9-47b2-8eca-4e97bf51b809", but I'm not sure if this is the "general" one or a one-time identifier).

No request was fired, by the way. The error blocked the execution of it.

**Comment by Pouja** [comment]
That just makes it weirder... But I am glad you were able to resolve your problem.
Ill keep this issue up until I figured out why it went wrong.

**Comment by dgroenewegen** [comment]
I found the problem: because the course is no longer available, I removed it from all the course groups/categories on the left. This causes the mentioned error in the client-side code. After adding it to one group again it seems to be working normally.

**Comment by Pouja** [comment]
Closing it then
