### ISSUE TITLE
Integration with TUDelft API.

### ISSUE THREAD

**Issue by janwillemm** [Pouja/tudscheduler#3]
Will implement this in the summer. Have already written a parser, if someone wants to implement it earlier, check it out:
https://github.com/janwillemm/studiegids/blob/master/studiegids.js

It's quite messy, but yeah, the TUD API is also messy..

**Comment by janwillemm** [comment]
Should definitely be cached btw, the API is really slow and every course needs it's own API call

**Comment by Pouja** [comment]
Sorry for responding so late, I guess I missed this in my github feed.
But saying

> Will implement this in the summer

Are you referring to the v1 api of TU Delft api?

**Comment by janwillemm** [comment]
TU Delft api I guess. I don't know what you mean with the v1 api

**Comment by Pouja** [comment]
Since the current TU Delft api is kinda lacking in structure and missing data we are going to switch to manual data, which will be rendered each year. So closing this issue.
